name = "webhook-receiver"
account_id = "profile"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
TRADE_WORKER_URL = "https://trade-worker.cryptolinx.workers.dev"
TELEGRAM_WORKER_URL = "https://telegram-worker.cryptolinx.workers.dev"

[observability]
enabled = true

# Secrets to be added with wrangler:
# wrangler secret put API_SECRET_KEY
# wrangler secret put INTERNAL_SERVICE_KEY
